spring.application.name=banking-document-verification-agent

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Rahitech@2024

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=loan_document_verification

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

document.storage.upload-dir=uploads/documents
